[toolchain]
package_manager = "yarn"
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sealed_auction = "2rTWXsHTnJdSKxJjdG1wDWdQYFFD3b6RfHbqi3VsR2dt"

[programs.devnet]
sealed_auction = "2rTWXsHTnJdSKxJjdG1wDWdQYFFD3b6RfHbqi3VsR2dt"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/bunny.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
